# Generated by Django 3.2.7 on 2021-10-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Mark Zuckerberg', max_length=50)),
                ('email', models.EmailField(help_text='Ex: Mark@gmail.com', max_length=60)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('country', models.CharField(help_text='Ex: Vietnam', max_length=50)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
